version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'nazoisgay'
      ADMIN_EMAIL: 'delta@floof.zone'
      PIHOLE_DNS: '1.1.1.1;8.8.8.8'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: always
  vscode:
    container_name: vscode
    image: ghcr.io/linuxserver/code-server
    environment:
      - PUID=1001
      - PGID=100
      - TZ=US/Central
    volumes:
      - ./vscode:/config
      - /home/delta/dev:/config/workspace
      - /home/delta/.ssh:/config/.ssh
    ports:
      - "8443:8443"
    restart: always
