version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  vscode:
    container_name: vscode
    image: ghcr.io/linuxserver/code-server
    user: 1000:1000
    environment:
      - PUID=1001
      - PGID=100
      - TZ=US/Central
    volumes:
      - ./vscode:/config
      - /home/delta/dev:/config/workspace
      - /home/delta/.ssh:/config/.ssh
    ports:
      - "8443:8443"
    restart: always
