# docker-compose up will not allow terminal input to the server
# instead use `docker-compose up -d && docker attach terraria`
version: "2.1"
services:
    terraria:
        image: debian:latest
        container_name: terraria
        volumes:
            - /home/delta/game/terraria:/terraria
            - /home/delta/game/terraria/localshare/Terraria:/root/.local/share/Terraria
        environment:
            - TZ=US/Central
        ports:
            - 7777:7777
        restart: on-failure
        command: "/terraria/tModLoaderServer -world /terraria/localshare/Terraria/ModLoader/Worlds/Home.wld -port 7777 -players 8"
