# docker-compose up will not allow terminal input to the server
# (!) this crashes it on startup!
# instead use `docker-compose run -p 7777:7777 terraria`
version: "2.1"
services:
    terraria:
        image: debian:stable-slim
        container_name: terraria
        tty: true
        restart: always
        volumes:
            - /home/delta/game/terraria:/terraria
            - /home/delta/game/terraria/localshare/Terraria:/root/.local/share/Terraria
        environment:
            - TZ=US/Central
        ports:
            - 7777:7777
        command: bash /terraria/start.sh
