# docker-compose up will not allow terminal input to the server
# (!) this crashes it on startup!
# instead use `docker-compose run -p 7777:7777 terraria`
version: "2.1"
services:
    terraria:
        image: frolvlad/alpine-mono:latest
        container_name: terraria
        tty: true
        restart: always
        volumes:
            - /home/delta/game/terraria/2021-01-19-tshock:/terraria
            - /home/delta/game/terraria/2021-01-19-tshock/localshare/Terraria:/root/.local/share/Terraria
        environment:
            - TZ=US/Central
        ports:
            - 7777:7777
        command: sh /terraria/start.sh
